version: "2"

services:
  java:
    tty: true # Enables debugging capabilities when attached to this container.
    image: "docker.io/bitnami/java:11-debian-10"
    command: "java -jar election/target/package.jar"
    ports:
      - 8080:8080
    volumes:
      - .:/app
    # command: ["tail", "-f", "/dev/null"] # To keep the container running
